# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

schedules:
- cron: 0 0 * * 0
  displayName: scheduled
  branches:
    include:
    - main
    - master
  always: true

resources:
- repo: self

variables:
  tag: '0.1'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'depuydt/apcupsd'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
          $(tag).$(Build.BuildNumber)
          latest
